In [61]:
import numpy as np

<h1>Krok pierwszy</h1>
To jest pierwszy notebook opisujący bibliotekę numpy

In [62]:
a = 56
b = 44
c = 90
tb = [a,b,c]

for n in tb:
    print(f"______[ - {n} - ]_______")

______[ - 56 - ]_______
______[ - 44 - ]_______
______[ - 90 - ]_______


In [63]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [65]:
np.empty(8)

array([3.31e-322, 3.95e-323, 4.45e-323, 5.93e-323, 5.93e-323, 4.40e-322,
 2.22e-322, 2.87e-322])

In [66]:
u = np.arange(1,89,3)
print(u)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88]


In [67]:
h = [54,7,3,7,3]
print(type(h))
print(type(u))

<class 'list'>
<class 'numpy.ndarray'>


In [68]:
k = np.linspace(0,10,num=5)
print(k)

[ 0.   2.5  5.   7.5 10. ]


In [69]:
lt= [6.6,5.,6,True,120,0.09,5e+45]
nplist = np.array(lt)
print(nplist)

[6.6e+00 5.0e+00 6.0e+00 1.0e+00 1.2e+02 9.0e-02 5.0e+45]


In [70]:
kr = {9,3,56,7}
knp = np.array(kr)
print(knp)
print(type(knp))

{56, 9, 3, 7}
<class 'numpy.ndarray'>


In [71]:
nb = [908,23,5,6,8,2,45,63,7,8,35,7,3,6,8,2,24,78,89,9]
nnp = np.array(nb)

In [72]:
nb.sort()
nb

[2, 2, 3, 5, 6, 6, 7, 7, 8, 8, 8, 9, 23, 24, 35, 45, 63, 78, 89, 908]

In [73]:
nnp.sort()
nnp

array([ 2, 2, 3, 5, 6, 6, 7, 7, 8, 8, 8, 9, 23,
 24, 35, 45, 63, 78, 89, 908])

In [74]:
a = np.array([1,5,89,65])
b = np.array([335,78,9])
c = np.array([12,7,8,34,123])

big = np.concatenate((a,b,c))
print(big)

[  1   5  89  65 335  78   9  12   7   8  34 123]


In [75]:
big.sort()
big

array([ 1, 5, 7, 8, 9, 12, 34, 65, 78, 89, 123, 335])

In [76]:
zx = [[5,7],[8,6]]
print(zx)
print(zx[0])
print(zx[0][0])

[[5, 7], [8, 6]]
[5, 7]
5


In [77]:
x = np.array([[67,8],[9,12]])
print(x)
print(x[0,1])

y = np.array([[12,89],[45,58]])

[[67  8]
 [ 9 12]]
8


In [78]:
p = np.concatenate((x,y),axis=0)
p

array([[67, 8],
 [ 9, 12],
 [12, 89],
 [45, 58]])

In [79]:
prosta = np.arange(12)
print(prosta)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [80]:
pp = prosta.reshape(3,4)
print(pp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
mc = np.array([[2,3],[5,6],[19,7]])
print(mc)
bc = mc.reshape([2,3])
print(bc)

[[ 2  3]
 [ 5  6]
 [19  7]]
[[ 2  3  5]
 [ 6 19  7]]


In [82]:
print(bc.shape)

(2, 3)


In [83]:
w = np.array([[1,2,3,4],[11,14,16,19],[46,42,5,67]])
w

array([[ 1, 2, 3, 4],
 [11, 14, 16, 19],
 [46, 42, 5, 67]])

In [84]:
print(w[w<5])

[1 2 3 4]


In [85]:
pc = (w>=5)
print(w[pc])

[11 14 16 19 46 42  5 67]


In [86]:
pv = (w%2==0)
print(w[pv])

[ 2  4 14 16 46 42]


In [87]:
c = w[(w>2)&(w<21)]
print(c)

[ 3  4 11 14 16 19  5]


In [88]:
s = w[(w<8) | (w>50)]
print(s)

[ 1  2  3  4  5 67]


In [89]:
dane = np.array([1,3,8])
ones = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [90]:
print(dane+ones)

[2 4 9]


In [91]:
print(dane-ones)

[0 2 7]


In [92]:
print(dane*tw)

[ 2  6 24]


In [93]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [94]:
tab = np.array([[1,6],[27,19]])
print(tab)

[[ 1  6]
 [27 19]]


In [95]:
print(tab.sum(axis=0))
print(tab.sum(axis=1))

[28 25]
[ 7 46]


In [96]:
print(tab.mean(axis=0))
print(tab.mean(axis=1))

[14.  12.5]
[ 3.5 23. ]


In [97]:
print(tab.std(axis=0))
print(tab.std(axis=1))

[13.   6.5]
[2.5 4. ]


In [98]:
print(tab*1.865)

[[ 1.865 11.19 ]
 [50.355 35.435]]


In [101]:
print(tab.max(axis=0))
print(tab.min())
print(tab.prod())

[27 19]
1
3078
